### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by davidak** [lokimo/py2k48#1]
i tried it with Python 2.7.5 on OS X 10.0.5 and got:

```
dkl:py2k48 davidak$ python py2k48.py
  File "py2k48.py", line 40
    print(j, end=' ')
                ^
SyntaxError: invalid syntax
```

**Comment by davidak** [comment]
it works with Python 3.4.3 on the same system.

**Comment by lokimo** [comment]
For python 2.\* you have to delete the Parentheses. But i don't know if there are some more issues, since I'm only familiar with python 3.*

**Comment by davidak** [comment]
so please add to the readme, that it only works with python 3.
